require("config.lazy")
require("config.telescope")
require("config.oil")
require("config.colourscheme")
require("config.lspconfig")
require("config.treesitter")
require("config.mason-config")
require("config.nvim-cmp")
require("lspconfig").lua_ls.setup {}
require("mason").setup()
require("mason-lspconfig").setup()
vim.cmd("set tabstop=2")
vim.cmd("set expandtab")
vim.cmd("set shiftwidth=2")
